name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore
        run: msbuild /t:restore

      - name: Build
        run: msbuild /t:publish /p:PublishDir=publish --nologo

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AutoShutdown 
          path: AutoShutdown/publish/*.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          files: AutoShutdown/publish/*.exe

      - name: Update release
        uses: richardsimko/update-tag@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}